version: "3.2"
services:

  redis:
    image: redis:alpine
    container_name: symfony-redis

  postgres:
    image: postgres:11.0-alpine
    container_name: symfony-postgres
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - POSTGRES_USER=symfony
      - POSTGRES_PASSWORD=symfony
      - POSTGRES_DB=symfony
    ports:
      - "5432:5432"

  webserver:
    image: nginx:alpine
    container_name: symfony-webserver
    working_dir: /var/www
    volumes:
        - .:/var/www
        - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"

  php-fpm:
    build: .docker/php-fpm
    container_name: symfony-php-fpm
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - DOCKER_UID=1000
      - DOCKER_GID=1000

